server {
    listen 80;
    server_name _;

    root /var/www/html;
    index index.php;

    location = / {
        return 302 /auth/login.php;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass academy_app:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
