server {
    listen 80;
    server_name ida-academy.duckdns.org;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name ida-academy.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/ida-academy.duckdns.org-0001/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ida-academy.duckdns.org-0001/privkey.pem;

    root /var/www/html;
    index index.php index.html;

    location = / {
        return 302 /auth/login.php;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
