version = 5.5.0
archive_dir = /etc/letsencrypt/archive/ida-academy.duckdns.org
cert = /etc/letsencrypt/live/ida-academy.duckdns.org/cert.pem
privkey = /etc/letsencrypt/live/ida-academy.duckdns.org/privkey.pem
chain = /etc/letsencrypt/live/ida-academy.duckdns.org/chain.pem
fullchain = /etc/letsencrypt/live/ida-academy.duckdns.org/fullchain.pem
[renewalparams]
account = 615bf6031d294911f3ad67d6a9d434a2
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
ida-academy.duckdns.org = /var/www/certbot
